#!/usr/bin/env python3
"""
package_submission.py
Automated submission packager and validator for Amazon ML Challenge 2026.
Creates 'unwanted_submission.zip' strictly matching the competition format:

unwanted_submission.zip
├── output/
│   ├── matching_results.tsv        # final matches (leaderboard upload)
│   └── candidate_pairs.tsv         # blocking candidate set
├── code/
│   └── business_entity_resolution/
│       ├── src/                    # complete source code
│       ├── README.md               # reproduction guide
│       └── requirements.txt        # pinned dependencies
└── Documentation_template.md       # methodology write-up
"""

import os
import shutil
import subprocess
import zipfile
import sys

def main():
    root_dir = os.path.abspath(os.path.dirname(__file__))
    target_dir = os.path.join(root_dir, "unwanted_submission")
    output_dir = os.path.join(target_dir, "output")
    code_dir = os.path.join(target_dir, "code", "business_entity_resolution")
    src_dir = os.path.join(code_dir, "src")

    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(src_dir, exist_ok=True)

    print("=" * 65)
    print("      AMAZON ML CHALLENGE 2026: SUBMISSION PACKAGER      ")
    print("      Team: unwanted | Package: unwanted_submission.zip  ")
    print("=" * 65)

    # 1. Sync code into unwanted_submission/code/business_entity_resolution/
    print("\n[1/4] Syncing latest codebase into submission directory...")
    src_origin = os.path.join(root_dir, "code", "src")
    if os.path.exists(src_origin):
        for fname in os.listdir(src_origin):
            if fname.endswith(".py"):
                shutil.copy2(os.path.join(src_origin, fname), os.path.join(src_dir, fname))
        print("  Copied Python source files to code/business_entity_resolution/src/")

    req_file = os.path.join(root_dir, "code", "requirements.txt")
    if os.path.exists(req_file):
        shutil.copy2(req_file, os.path.join(code_dir, "requirements.txt"))
        print("  Copied requirements.txt")

    readme_file = os.path.join(root_dir, "code", "README.md")
    if os.path.exists(readme_file):
        shutil.copy2(readme_file, os.path.join(code_dir, "README.md"))
        print("  Copied README.md")

    doc_file = os.path.join(root_dir, "Documentation_template.md")
    if os.path.exists(doc_file):
        shutil.copy2(doc_file, os.path.join(target_dir, "Documentation_template.md"))
        print("  Copied Documentation_template.md to submission root")

    # 2. Check and copy output TSVs
    print("\n[2/4] Checking output TSV files...")
    possible_match_paths = [
        os.path.join(root_dir, "output", "test", "matching_results.tsv"),
        os.path.join(root_dir, "output", "matching_results.tsv"),
        os.path.join(output_dir, "matching_results.tsv")
    ]
    possible_cand_paths = [
        os.path.join(root_dir, "output", "test", "candidate_pairs.tsv"),
        os.path.join(root_dir, "output", "candidate_pairs.tsv"),
        os.path.join(output_dir, "candidate_pairs.tsv")
    ]

    match_src = next((p for p in possible_match_paths if os.path.exists(p) and p != os.path.join(output_dir, "matching_results.tsv")), None)
    cand_src = next((p for p in possible_cand_paths if os.path.exists(p) and p != os.path.join(output_dir, "candidate_pairs.tsv")), None)

    dest_match = os.path.join(output_dir, "matching_results.tsv")
    dest_cand = os.path.join(output_dir, "candidate_pairs.tsv")

    if match_src and os.path.abspath(match_src) != os.path.abspath(dest_match):
        shutil.copy2(match_src, dest_match)
        print(f"  Copied matching_results.tsv from {match_src}")
    elif os.path.exists(dest_match):
        print(f"  Found matching_results.tsv ({os.path.getsize(dest_match) / 1024 / 1024:.2f} MB)")
    else:
        print("  Notice: matching_results.tsv not found yet (will be generated by Section 6 test inference).")

    if cand_src and os.path.abspath(cand_src) != os.path.abspath(dest_cand):
        shutil.copy2(cand_src, dest_cand)
        print(f"  Copied candidate_pairs.tsv from {cand_src}")
    elif os.path.exists(dest_cand):
        print(f"  Found candidate_pairs.tsv ({os.path.getsize(dest_cand) / 1024 / 1024:.2f} MB)")
    else:
        print("  Notice: candidate_pairs.tsv not found yet (will be generated by Section 6 test inference).")

    # 3. Validate outputs if present
    if os.path.exists(dest_match):
        print("\n[3/4] Validating outputs with official competition validator...")
        val_script = os.path.join(root_dir, "code", "src", "validate_submission.py")
        test_dir = None
        for cand_dir in ["dataset/test", "6ab10eb3b23ba_student_resource/student_resource/dataset/test"]:
            if os.path.exists(os.path.join(root_dir, cand_dir)):
                test_dir = os.path.join(root_dir, cand_dir)
                break
        
        if os.path.exists(val_script) and test_dir:
            cmd = [
                sys.executable, val_script,
                "--matching", dest_match,
                "--candidate", dest_cand if os.path.exists(dest_cand) else "",
                "--test-dir", test_dir
            ]
            cmd = [c for c in cmd if c]
            ret = subprocess.run(cmd)
            if ret.returncode != 0:
                print("\nWarning: Validation checks flagged issues. Review output above.")
        else:
            print("  Test dataset directory not found locally; skipping validator.")
    else:
        print("\n[3/4] Skipping validator (run test inference first to generate matching_results.tsv).")

    # 4. Create ZIP archive
    print("\n[4/4] Creating submission zip archive: unwanted_submission.zip...")
    zip_path = os.path.join(root_dir, "unwanted_submission.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(target_dir):
            for file in files:
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, target_dir)
                zf.write(full_path, arcname=rel_path)

    zip_size_mb = os.path.getsize(zip_path) / (1024 * 1024)
    print(f"\nSUCCESS! Created: {zip_path} ({zip_size_mb:.2f} MB)")
    print("Archive contains:")
    with zipfile.ZipFile(zip_path, "r") as zf:
        for info in zf.infolist()[:15]:
            print(f"  - {info.filename}")
        if len(zf.infolist()) > 15:
            print(f"  ... and {len(zf.infolist()) - 15} more files")
    print("=" * 65 + "\n")

if __name__ == "__main__":
    main()
